spring:
  profiles:
    active: dev
  aop:
    proxy-target-class: true
  rabbitmq:
    host: 120.78.179.251
    username: admin
    password: admin
    virtual-host: u2licai
    listener:
      simple:
        acknowledge-mode: auto
#    publisher-confirms: true
  data:
    mongodb:
      host: 120.78.179.251
      port: 27017
      database: mongodb_test

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: test-u2
    password: abc+123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maxLifetime: 1765000 #一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒以上
      maximumPoolSize: 15 #连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
mybatis-plus:
  mapper-locations: classpath*:/com/jack/dal/xml/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jack.dal.dao
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    logic-delete-value: 0
    logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    
#logging
logging:
  level:
    root: debug
server:
  port: 3333


---
# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.1.79/u2licai-dev?zeroDateTimeBehavior=convertToNull
---
# 测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://192.168.0.12:3306/

---
# 待发布环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.0.13:3306/
---
# 生产环境配置
spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://192.168.0.13:3306/